import { Command } from "commander";
import chalk from "chalk";
import Table from "cli-table3";
import { readStatsCache, getModelPricing } from "@tokenscore/core";
import { formatTokens, formatCost, header, kv } from "../helpers.js";

export function registerStatsCommand(program: Command): void {
  program
    .command("stats")
    .description("Show Claude Code stats from stats-cache.json")
    .option("--json", "Output as JSON")
    .action(async (opts) => {
      const cache = await readStatsCache();
      if (!cache) {
        console.log(chalk.yellow("No stats-cache.json found. This file is generated by Claude Code."));
        return;
      }

      if (opts.json) {
        console.log(JSON.stringify(cache, null, 2));
        return;
      }

      header("Claude Code Global Stats");

      kv("Data since", cache.firstSessionDate?.slice(0, 10) ?? "unknown");
      kv("Last computed", cache.lastComputedDate);
      kv("Total sessions", cache.totalSessions);
      kv("Total messages", cache.totalMessages);

      if (cache.longestSession) {
        const durMin = Math.round(cache.longestSession.duration / 60_000);
        kv("Longest session", `${durMin} min (${cache.longestSession.messageCount} messages)`);
      }

      // Model usage breakdown
      console.log();
      console.log(chalk.bold("  Model Usage:"));

      const modelTable = new Table({
        head: ["Model", "Input", "Output", "Cache Read", "Cache Create", "Est. Cost"],
        style: { head: ["cyan"] },
      });

      let grandTotal = 0;

      for (const [modelId, usage] of Object.entries(cache.modelUsage)) {
        const pricing = getModelPricing(modelId);
        let cost = 0;
        if (pricing) {
          cost =
            (usage.inputTokens / 1e6) * pricing.input +
            (usage.outputTokens / 1e6) * pricing.output +
            (usage.cacheReadInputTokens / 1e6) * pricing.cacheRead +
            (usage.cacheCreationInputTokens / 1e6) * pricing.cacheCreation;
        }
        grandTotal += cost;

        modelTable.push([
          modelId,
          formatTokens(usage.inputTokens),
          formatTokens(usage.outputTokens),
          formatTokens(usage.cacheReadInputTokens),
          formatTokens(usage.cacheCreationInputTokens),
          formatCost(cost),
        ]);
      }

      console.log(modelTable.toString());
      console.log();
      kv("Total estimated cost", formatCost(grandTotal));

      // Activity heatmap by hour
      if (cache.hourCounts && Object.keys(cache.hourCounts).length > 0) {
        console.log();
        console.log(chalk.bold("  Activity by hour:"));
        const maxCount = Math.max(...Object.values(cache.hourCounts));
        for (let h = 0; h < 24; h++) {
          const count = cache.hourCounts[String(h)] ?? 0;
          const barLen = maxCount > 0 ? Math.round((count / maxCount) * 30) : 0;
          const bar = "█".repeat(barLen);
          const hourStr = String(h).padStart(2, "0");
          const countStr = count > 0 ? ` ${count}` : "";
          console.log(`    ${hourStr}:00 ${chalk.cyan(bar)}${chalk.gray(countStr)}`);
        }
      }

      console.log();
    });
}
